[[entity]]

[entity.components.Text]
id = "header"
text = "LEVEL  NAME  SCORE"
font_face = { font = "joystix", options.size = 55.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 70, y = -120 }
origin = "TopLeft"
pivot = "MiddleLeft"


[[entity]]

[entity.components.Text]
id = "score01"
text = "1  AAAAAA      0"
font_face = { font = "joystix", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 885, y = -190 }
origin = "TopLeft"
pivot = "MiddleRight"


[[entity]]

[entity.components.Text]
id = "score02"
text = "2  AAAAAA      0"
font_face = { font = "joystix", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 885, y = -240 }
origin = "TopLeft"
pivot = "MiddleRight"


[[entity]]

[entity.components.Text]
id = "score03"
text = "3  AAAAAA      0"
font_face = { font = "joystix", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 885, y = -290 }
origin = "TopLeft"
pivot = "MiddleRight"


[[entity]]

[entity.components.Text]
id = "score04"
text = "4  AAAAAA      0"
font_face = { font = "joystix", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 885, y = -340 }
origin = "TopLeft"
pivot = "MiddleRight"


[[entity]]

[entity.components.Text]
id = "score05"
text = "5  AAAAAA      0"
font_face = { font = "joystix", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 885, y = -390 }
origin = "TopLeft"
pivot = "MiddleRight"


[[entity]]

[entity.components.Text]
id = "score06"
text = "6  AAAAAA      0"
font_face = { font = "joystix", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 885, y = -440 }
origin = "TopLeft"
pivot = "MiddleRight"


[[entity]]

[entity.components.Text]
id = "score07"
text = "7  AAAAAA      0"
font_face = { font = "joystix", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 885, y = -490 }
origin = "TopLeft"
pivot = "MiddleRight"


[[entity]]

[entity.components.Text]
id = "score08"
text = "8  AAAAAA      0"
font_face = { font = "joystix", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 885, y = -540 }
origin = "TopLeft"
pivot = "MiddleRight"


[[entity]]

[entity.components.Text]
id = "score09"
text = "9  AAAAAA      0"
font_face = { font = "joystix", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 885, y = -590 }
origin = "TopLeft"
pivot = "MiddleRight"


[[entity]]

[entity.components.Text]
id = "score10"
text = "10  AAAAAA      0"
font_face = { font = "joystix", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 885, y = -640 }
origin = "TopLeft"
pivot = "MiddleRight"


[[entity]]

[entity.components.Text]
id = "cursor"
text = "\u25ba"
font_face = { font = "hack", options.size = 50.0 }
color = [255, 0, 0, 0]

[entity.components.UITransform]
translation = { x = 50, y = -390 }
origin = "TopLeft"
pivot = "MiddleLeft"


[[entity]]

[entity.components.Text]
id = "arrow_up"
text = "\u25b2"
font_face = { font = "hack", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 0, y = -50 }
origin = "TopMiddle"
pivot = "TopMiddle"


[[entity]]

[entity.components.Text]
id = "arrow_down"
text = "\u25bc"
font_face = { font = "hack", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 0, y = 10 }
origin = "BottomMiddle"
pivot = "BottomMiddle"
