[[entity]]

[entity.components.SpriteRender]
sprite_sheet_name = "background"
sprite_number = 0

[entity.components.Transform]
translation = { x = 0.0, y = 0.0 }
origin = "Middle"
depth = 2.0

[entity.components.Background]


[[entity]]

[entity.components.Text]
id = "level_complete"
text = "LEVEL COMPLETE"
font_face = { font = "joystix", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 0, y = 0 }
origin = "Middle"
