[[entity]]

[entity.components.Text]
id = "title"
text = "Sokoban"
font_face = { font = "joystix", options.size = 75.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 650 }


[[entity]]

[entity.components.Text]
id = "cursor_start"
text = "\u25ba"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 295, y = 500 }


[[entity]]

[entity.components.Text]
id = "cursor_view_highscores"
text = "\u25ba"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 40, y = 400 }


[[entity]]

[entity.components.Text]
id = "cursor_view_solutions"
text = "\u25ba"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 65, y = 300 }


[[entity]]

[entity.components.Text]
id = "cursor_choose_package"
text = "\u25ba"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 65, y = 200 }


[[entity]]

[entity.components.Text]
id = "cursor_exit"
text = "\u25ba"
font_face = { font = "hack", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 315, y = 100 }


[[entity]]

[entity.components.Text]
id = "start"
text = "START"
font_face = { font = "joystix", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 500 }


[[entity]]

[entity.components.SpriteRender]
fill = { width = 280, height = 60 }

[entity.components.Transform]
translation = { x = 480, y = 500 }

[entity.components.MouseReactive]
id = "start"


[[entity]]

[entity.components.Text]
id = "view_highscores"
text = "VIEW HIGHSCORES"
font_face = { font = "joystix", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 400 }


[[entity]]

[entity.components.SpriteRender]
fill = { width = 790, height = 60 }

[entity.components.Transform]
translation = { x = 480, y = 400 }

[entity.components.MouseReactive]
id = "view_highscores"


[[entity]]

[entity.components.Text]
id = "view_solutions"
text = "VIEW SOLUTIONS"
font_face = { font = "joystix", options.size = 60.0 }
color = [255, 255, 255, 75]

[entity.components.UITransform]
translation = { x = 480, y = 300 }


[[entity]]

[entity.components.SpriteRender]
fill = { width = 740, height = 60 }

[entity.components.Transform]
translation = { x = 480, y = 300 }

[entity.components.MouseReactive]
id = "view_solutions"


[[entity]]

[entity.components.Text]
id = "choose_package"
text = "CHOOSE PACKAGE"
font_face = { font = "joystix", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 200 }


[[entity]]

[entity.components.SpriteRender]
fill = { width = 740, height = 60 }

[entity.components.Transform]
translation = { x = 480, y = 200 }

[entity.components.MouseReactive]
id = "choose_package"


[[entity]]

[entity.components.Text]
id = "exit"
text = "EXIT"
font_face = { font = "joystix", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 100 }


[[entity]]

[entity.components.SpriteRender]
fill = { width = 240, height = 60 }

[entity.components.Transform]
translation = { x = 480, y = 100 }

[entity.components.MouseReactive]
id = "exit"
