[[entity]]

[entity.components.Text]
id = "header"
text = "LEVEL    STEPS"
font_face = { font = "joystix", options.size = 55.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 165, y = -120 }
origin = "TopLeft"
pivot = "MiddleLeft"


[[entity]]

[entity.components.Text]
id = "steps01"
text = "1      0"
font_face = { font = "joystix", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 785, y = -190 }
origin = "TopLeft"
pivot = "MiddleRight"


[[entity]]

[entity.components.Text]
id = "steps02"
text = "2      0"
font_face = { font = "joystix", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 785, y = -240 }
origin = "TopLeft"
pivot = "MiddleRight"


[[entity]]

[entity.components.Text]
id = "steps03"
text = "3      0"
font_face = { font = "joystix", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 785, y = -290 }
origin = "TopLeft"
pivot = "MiddleRight"


[[entity]]

[entity.components.Text]
id = "steps04"
text = "4      0"
font_face = { font = "joystix", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 785, y = -340 }
origin = "TopLeft"
pivot = "MiddleRight"


[[entity]]

[entity.components.Text]
id = "steps05"
text = "5      0"
font_face = { font = "joystix", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 785, y = -390 }
origin = "TopLeft"
pivot = "MiddleRight"


[[entity]]

[entity.components.Text]
id = "steps06"
text = "6      0"
font_face = { font = "joystix", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 785, y = -440 }
origin = "TopLeft"
pivot = "MiddleRight"


[[entity]]

[entity.components.Text]
id = "steps07"
text = "7      0"
font_face = { font = "joystix", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 785, y = -490 }
origin = "TopLeft"
pivot = "MiddleRight"


[[entity]]

[entity.components.Text]
id = "steps08"
text = "8      0"
font_face = { font = "joystix", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 785, y = -540 }
origin = "TopLeft"
pivot = "MiddleRight"


[[entity]]

[entity.components.Text]
id = "steps09"
text = "9      0"
font_face = { font = "joystix", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 785, y = -590 }
origin = "TopLeft"
pivot = "MiddleRight"


[[entity]]

[entity.components.Text]
id = "steps10"
text = "10      0"
font_face = { font = "joystix", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 785, y = -640 }
origin = "TopLeft"
pivot = "MiddleRight"


[[entity]]

[entity.components.Text]
id = "cursor"
text = "\u25ba"
font_face = { font = "hack", options.size = 50.0 }
color = [255, 0, 0, 0]

[entity.components.UITransform]
translation = { x = 150, y = -390 }
origin = "TopLeft"
pivot = "MiddleLeft"


[[entity]]

[entity.components.Text]
id = "arrow_up"
text = "\u25b2"
font_face = { font = "hack", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 0, y = -50 }
origin = "TopMiddle"
pivot = "TopMiddle"


[[entity]]

[entity.components.Text]
id = "arrow_down"
text = "\u25bc"
font_face = { font = "hack", options.size = 50.0 }
color = [255, 255, 255, 0]

[entity.components.UITransform]
translation = { x = 0, y = 10 }
origin = "BottomMiddle"
pivot = "BottomMiddle"
